[en_US]
v = "Hide copied codes from suggestions and previews"

[es_ES]
v = "Ocultar códigos copiados de sugerencias y vistas previas"

[ru_RU]
v = "Скрывать скопированные коды из предложений и предпросмотров"
