[en_US]
v = "Move your finger as randomly as possible across the screen. The longer you move it, the better. This significantly increases the cryptographic strength of the encryption keys."

[es_ES]
v = "Mueve el dedo por la pantalla de la forma más aleatoria posible. Cuanto más tiempo lo muevas, mejor. Esto aumenta significativamente la seguridad criptográfica de las claves de cifrado."

[ru_RU]
v = "Двигайте пальцем по экрану как можно более хаотично. Чем дольше вы двигаете, тем лучше. Это значительно повышает криптографическую стойкость ключей шифрования."
